language: ruby
sudo: false
cache: bundler
matrix:
  include:
    - # GitHub Pages
      rvm: 2.5.3
      env: GH_PAGES=true
rvm:
  - 2.6
  - 2.4
before_install:
- gem update --system
before_script: bundle update
script: script/cibuild
